# ------------------------------------------------------------------------------
# Travis CI scripts 
# Copyright(c) pgRouting Contributors
#
# Main configuration
# ------------------------------------------------------------------------------


language: python


notifications:
  email:
    on_failure: project@pgrouting.org


# excecuted. So things have to be tested oe by one.
addons:
  apt:
    packages:
      - cmake
      - python-sphinx


script: 
  - cd docs ; make html ; ls _build

